CREATE TABLE  "MY_LIST_KEEPER" 
   (	"LIST_ITEM_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"MY_CATEGORY" VARCHAR2(40) NOT NULL ENABLE, 
	"ITEM_VALUE" VARCHAR2(50), 
	 CONSTRAINT "MY_LIST_KEEPER_PK" PRIMARY KEY ("LIST_ITEM_ID") ENABLE
   )
/


CREATE SEQUENCE   "MY_LIST_KEEPER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE
/

CREATE OR REPLACE TRIGGER  "BI_MY_LIST_KEEPER" 
  before insert on "MY_LIST_KEEPER"               
  for each row  
begin   
  if :NEW."LIST_ITEM_ID" is null then 
    select "MY_LIST_KEEPER_SEQ".nextval into :NEW."LIST_ITEM_ID" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_MY_LIST_KEEPER" ENABLE
/


